#!/usr/bin/env bash
# write a Bash script that will display information about the subdomains

dns_config () {
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  dns_config "$1" "www"
  dns_config "$1" "lb-01"
  dns_config "$1" "web-01"
  dns_config "$1" "web-02"
elif [ "$#" == 2 ]
then
  dns_config "$1" "$2"
fi
# Helps get the information about a specific subdomain for our website.

print_domain_info() {
	record_type=$(dig "$2.$1" | grep -A1 ';; ANSWER SECTION:' | awk '{printf "%s", $4}')
	ip=$(dig "$2.$1" | grep -A1 ';; ANSWER SECTION:' | awk '{printf "%s", $5}')
	printf "The subdomain %s is a %s record and points to %s\n" "$2" "$record_type" "$ip"
}

if [ -z "$2" ]
then
	for sub in "www" "lb-01" "web-01" "web-02"
	do
		print_domain_info "$1" "$sub"
	done
else
	print_domain_info "$1" "$2"
fi
# write a Bash script that will display information about the subdomains

dns_config () {
    script=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $script" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ "$#" == 1 ]
then
  dns_config "$1" "www"
  dns_config "$1" "lb-01"
  dns_config "$1" "web-01"
  dns_config "$1" "web-02"
elif [ "$#" == 2 ]
then
  dns_config "$1" "$2"
fi
